import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import CharacterIntegrationsSettingsSection from './CharacterIntegrationsSettingsSection';

const mocks = vi.hoisted(() => ({
  getAdminWarcraftLogsCredentials: vi.fn(),
  getIntegrationSettings: vi.fn(),
  removeAdminWarcraftLogsCredentials: vi.fn(),
  removeWarcraftLogsCredentials: vi.fn(),
  saveAdminWarcraftLogsCredentials: vi.fn(),
  saveWarcraftLogsCredentials: vi.fn(),
  testWarcraftLogsCredentials: vi.fn(),
  updateIntegrationSettings: vi.fn(),
}));

vi.mock('../../lib/api', () => mocks);

const settings = (warcraftLogsEnabled = false) => ({
  raider_io_enabled: true,
  warcraft_logs_enabled: warcraftLogsEnabled,
  warcraft_logs: {
    user_configured: false,
    user_client_id: null,
    effective_source: null,
    environment_configured: false,
    admin_configured: false,
  },
});

describe('CharacterIntegrationsSettingsSection', () => {
  beforeEach(() => {
    mocks.getIntegrationSettings.mockResolvedValue(settings());
    mocks.updateIntegrationSettings.mockResolvedValue(settings());
    mocks.testWarcraftLogsCredentials.mockResolvedValue({ status: 'ok' });
    mocks.saveWarcraftLogsCredentials.mockResolvedValue({ status: 'saved', enabled: true });
  });

  afterEach(() => {
    cleanup();
    vi.clearAllMocks();
  });

  it('defaults Raider.IO on and Warcraft Logs off', async () => {
    render(<CharacterIntegrationsSettingsSection isHostedPrivate={false} isAdmin={false} />);

    await waitFor(() => expect(mocks.getIntegrationSettings).toHaveBeenCalledOnce());

    expect(screen.getByRole('checkbox', { name: /Raider\.IO/ })).toBeChecked();
    expect(screen.getByRole('checkbox', { name: /Warcraft Logs/ })).not.toBeChecked();
    expect(screen.getByText(/Application name:/)).toBeInTheDocument();
    expect(screen.getByText(/Redirect URLs:/)).toBeInTheDocument();
    expect(screen.getByText(/Warcraft Logs requires a value/)).toBeInTheDocument();
    expect(screen.getByText(window.location.origin)).toBeInTheDocument();
    expect(screen.getByText(/Public Client:/)).toBeInTheDocument();
    expect(screen.getByText(/Paste the Client ID generated by Warcraft Logs/)).toBeInTheDocument();
    expect(screen.getByText(/Paste the generated Client Secret/)).toBeInTheDocument();
  });

  it('saves personal credentials and reflects the automatic enablement', async () => {
    mocks.getIntegrationSettings
      .mockResolvedValueOnce(settings())
      .mockResolvedValueOnce(settings(true));

    render(<CharacterIntegrationsSettingsSection isHostedPrivate={false} isAdmin={false} />);

    fireEvent.change(screen.getByPlaceholderText('Warcraft Logs client ID'), {
      target: { value: 'client-id' },
    });
    fireEvent.change(screen.getByPlaceholderText('Warcraft Logs client secret'), {
      target: { value: 'client-secret' },
    });
    fireEvent.click(screen.getByRole('button', { name: 'Save credentials' }));

    await waitFor(() =>
      expect(mocks.saveWarcraftLogsCredentials).toHaveBeenCalledWith('client-id', 'client-secret')
    );
    await waitFor(() =>
      expect(screen.getByRole('checkbox', { name: /Warcraft Logs/ })).toBeChecked()
    );
  });
});
